release:
  image: node:lts-alpine3.18
  stage: deploy
  variables:
    CI_USERNAME: release-it
    CI_EMAIL: noreply@hansemerkur.de
  before_script:
    - apk add --no-cache git openssh curl
    - eval `ssh-agent -s`
    - echo "${RELEASE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - sleep 2
    - ssh -oStrictHostKeyChecking=no git@gitpro.hanse-merkur.de
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git checkout $CI_COMMIT_REF_NAME
    - git pull origin $CI_BUILD_REF_NAME -X theirs
    - git remote set-url origin "git@${CI_SERVER_HOST}:$CI_PROJECT_PATH.git"
    - git config --global user.name "${CI_USERNAME}"
    - git config --global user.email "${CI_EMAIL}"
    - npm config set proxy $HTTP_PROXY
    - npm config set https-proxy $HTTPS_PROXY
    - npm install -g release-it
    - npm install --save-dev @release-it/bumper
    - npm install --save-dev @release-it/conventional-changelog
    - npm install --global web-ext
  script:
    - web-ext build --source-dir ./extension --artifacts-dir ./artifacts --filename bookmarkSynch.zip
    - release-it --npm.skipChecks --no-npm.publish --ci
  when: manual
  dependencies: [ ]
  except:
    - tags
    - schedules
  only:
    - main
  artifacts:
    paths:
      - ./artifacts/bookmarkSynch.zip
